Fixed check for number of tickets when booking
careerfairsystems/nexpo-backend-nova pull request #159
Opened 2024-04-19 09:30 UTC by pizzaburgare

Added test that checks that user with 5 tickets cannot book any more.

2024-04-22 08:57 UTC, trilleplay requested changes

2024-04-22 08:57 UTC, trilleplay commented on Nexpo/Controllers/Events/TicketsController.cs
> +            int noTickets = (await _ticketRepo.GetAllForUser(userId)).Count();
Jag tänker kanske snett här, men tickets för event som har passerat rensas nog inte. Så vi vill snarare räkna mängden tickets som hör till event som ännu inte passerat. Alltså behöver du nog kolla på det tillhörande Event objekten till tickets som användaren har.

2024-04-23 22:17 UTC, LeoFjatstrom commented
![](https://github.trello.services/images/mini-trello-icon.png) [Maxtak på vilka event man kan anmäla sig till](https://trello.com/c/KPbogj6d/5-maxtak-p%C3%A5-vilka-event-man-kan-anm%C3%A4la-sig-till)

2024-05-07 16:13 UTC, trilleplay requested changes

2024-05-07 16:13 UTC, trilleplay commented on Nexpo.Tests/Controllers/TicketsControllerTest.cs
> +            // Student2 already has 5 tickets but not -7
Väldigt otydlig kommentar. Går att tolka på olika sätt som att en användare har 5 tickets men inte -7 stycken tickets. Eller att dem har tickets till event 5 men inte -7. (Vilket är min gissning baserat på att vi skapar upp ett jsonobject med `eventid` satt till `-7`.

2024-05-07 17:16 UTC, LeoFjatstrom approved these changes

2024-05-07 17:17 UTC, merged